# Generated by Django 2.2.17 on 2020-11-15 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ('-start_date', '-end_date')},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='polls.Question', verbose_name='Вопрос'),
        ),
    ]
