# Generated by Django 2.2.17 on 2020-11-15 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polls', '0002_auto_20201115_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(unique=True, verbose_name='id пользователя')),
                ('text_answer', models.CharField(blank=True, max_length=500, verbose_name='Ответ')),
                ('multi_choice_answer', models.ManyToManyField(blank=True, related_name='user_answer_multi_choice', to='polls.Choice')),
                ('one_choice_answer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_answer_one_choice', to='polls.Choice', verbose_name='Выбранный вариант ответа')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answer', to='polls.Question', verbose_name='Вопрос')),
            ],
        ),
    ]
