# Generated by Django 2.2.17 on 2020-11-15 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_answers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='multi_choice_answer',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_answer_multi_choice', to='polls.Choice'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='one_choice_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_answer_one_choice', to='polls.Choice', verbose_name='Выбранный вариант ответа'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='text_answer',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ответ'),
        ),
    ]
