# Generated by Django 2.2.17 on 2020-11-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_answers', '0003_auto_20201115_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='multi_choice_answer',
            field=models.ManyToManyField(related_name='user_answer_multi_choice', to='polls.Choice'),
        ),
    ]
