# Generated by Django 2.2.17 on 2020-11-15 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20201115_1453'),
        ('user_answers', '0004_auto_20201115_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='poll',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='user_answer', to='polls.Poll', verbose_name='Опрос'),
            preserve_default=False,
        ),
    ]
